spring:
  application:
    name: labpay
  datasource:
    url: ${DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

app:
  jwt:
    secret: "nobodygonnastealmyjwtsecretisnthe1234567"
    access-token-expiration-minutes: 60